# Generated by Django 4.0.6 on 2022-08-02 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='meetup',
            name='image',
            field=models.ImageField(default='test', upload_to='', verbose_name='image'),
            preserve_default=False,
        ),
    ]
